Update task17_FlutterFirebase.yml

diff --git a/.github/workflows/task17_FlutterFirebase.yml b/.github/workflows/task17_FlutterFirebase.yml
--- a/.github/workflows/task17_FlutterFirebase.yml
+++ b/.github/workflows/task17_FlutterFirebase.yml
@@ -34,11 +34,16 @@ jobs:
         with:
           channel: "stable"
 
-      - name: Enable Dart Analytics
-        run: dart --enable-analytics
-
       - name: Set working directory to the Flutter project
-        run: cd /home/runner/work/DevOpsGYMBatch3/DevOpsGYMBatch3/task17/task17
+        run: |
+          cd /home/runner/work/DevOpsGYMBatch3/DevOpsGYMBatch3/task17/task17  # Adjust the path to the root of your Flutter project
+
+      - name: Check if pubspec.yaml exists
+        run: |
+          if [ ! -f pubspec.yaml ]; then
+            echo "pubspec.yaml file not found."
+            exit 1
+          fi
 
       - name: Get Flutter Dependencies
         run: |
