Update task17_FlutterFirebase.yml

diff --git a/.github/workflows/task17_FlutterFirebase.yml b/.github/workflows/task17_FlutterFirebase.yml
--- a/.github/workflows/task17_FlutterFirebase.yml
+++ b/.github/workflows/task17_FlutterFirebase.yml
@@ -38,7 +38,7 @@ jobs:
 
       # **Change:** Add a step to check if the pubspec.yaml file exists.
       - name: Check if pubspec.yaml exists
-        run: if [ ! -f pubspec.yaml ]; then echo "pubspec.yaml file not found." && exit 1; fi
+        run: if [ ! -f task17/task17/pubspec.yaml ]; then echo "pubspec.yaml file not found." && exit 1; fi
 
       - name: Get Flutter Dependencies
         run: |
